# Generated by Django 3.2.9 on 2021-11-24 19:54

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_idx', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=45)),
                ('gold', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
            managers=[
                ('objects', User.models.UserManager()),
            ],
        ),
    ]
